<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="System.Reflection.Emit" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageVersion Include="BobDust.Core" Version="0.10.4" />
        <PackageVersion Include="BobDust.Rpc.Sockets" Version="0.10.4" />
        <PackageVersion Include="BobDust.Rpc.Sockets.Abstractions" Version="0.10.4" />
    </ItemGroup>
</Project>