<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

        <!-- Versioning & Metadata -->
        <Version>0.10.5</Version>
        <Authors>BobDust</Authors>
        <Company>BobDust</Company>
        <Copyright>Copyright ©BobDust 2012</Copyright>
        <Description>BobDust libraries</Description>
        <Product>BobDust.Rpc</Product>
        <!-- Specify the custom nuspec file if not done at project level -->
        <!-- <NuspecFile>$(MSBuildThisFileDirectory)package.nuspec</NuspecFile> -->

        <!-- Package Configuration -->
        <RepositoryUrl>https://github.com/bobdust/BobDust.Rpc</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>dotnet;nuget;shared-utils;tcp-rpc</PackageTags>
        <PackageVersion>0.10.5</PackageVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <!-- Assembly versions -->
        <AssemblyVersion>0.10.5</AssemblyVersion>
        <!-- FileVersion may include build number from CI -->
        <FileVersion>0.10.5</FileVersion>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>