<Project>
    <PropertyGroup>

        <Company>BobDust</Company>
        <Description>BobDust libraries</Description>

        <PackageId>$(AssemblyTitle.Replace(" ", "_"))</PackageId>
        <Authors>$(Company)</Authors>

        <!-- Assembly versions -->
        <AssemblyVersion>0.10.0</AssemblyVersion>

        <!-- FileVersion may include build number from CI -->
        <FileVersion>0.10.0</FileVersion>
    </PropertyGroup>
</Project>