<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="System.Runtime.Serialization.Formatters" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <PackageVersion Include="BobDust.Core" Version="1.0.0" />
        <PackageVersion Include="BobDust.Rpc.Sockets" Version="1.0.0" />
        <PackageVersion Include="BobDust.Rpc.Sockets.Abstractions" Version="1.0.0" />
    </ItemGroup>
</Project>